version: '3'
services:
  node:
    image: "node:8"
    container_name: "node"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./backend:/home/node/app
    command: "npm start"

  web:
    image: nginx
    container_name: "webservice"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log:/var/log/nginx
    command: /bin/bash -c "exec nginx -g 'daemon off;'"
    ports:
      - "80:80"
    depends_on:
      - node
